### ISSUE TITLE
统计图

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v1#14]
掉率随时间变化、过去24小时上传量等统计图。

**Comment by ChaosNiku** [comment]
+ 掉率时间变化使用折线
+ 上传量统计使用柱状
+ 掉率随时间变化的每个采样点时间间隔取多少合适？1hr？还是做成用户可自由选择时间间隔
+ 掉率随时间变化统计图显示是否只针对某一素材即可还是考虑详细化精确到某一素材在特定关卡掉落

**Comment by AlvISsReimu** [comment]
> * 掉率随时间变化的每个采样点时间间隔取多少合适？1hr？还是做成用户可自由选择时间间隔

1hr内的上传量较少，我倾向为1d，具体可以找几个人气作战选取不同interval看看掉率变化效果。

> * 掉率随时间变化统计图显示是否只针对某一素材即可还是考虑详细化精确到某一素材在特定关卡掉落

考虑细化到某素材在某作战下的掉率变化。
关于显示方式，我认为可以在查看结果（无论是按作战还是按素材）表格的每行最右侧加一个按钮，点击后跳出pop-up来展示掉率变化折线图。不过要求样本数要大于一定阈值，否则没什么意义。
