### ISSUE TITLE
感觉开发个图片识别功能还是蛮不错的？

### ISSUE THREAD

**Issue by redhood0** [penguin-statistics/frontend-v1#23]
![Snipaste_2019-07-23_23-47-47](https://user-images.githubusercontent.com/45115367/61726957-17ae0380-ada5-11e9-9654-cce938420e74.png)

我看到官网上有说过后续会开发类似的功能，用户打完之后直接把战斗结算上传也是挺省事的，就是图像文字的识别技术个人开发好像有点难度，调百度图片的ai匹配接口估计还是挺好实现的，但是并发大的话估计费用又是不小的开销，而且不排除恶意上传的用户，但是感觉这个功能总的来说还是利大于弊的，希望站长有空可以开发一下：D

**Comment by redhood0** [comment]
![xxxx](https://user-images.githubusercontent.com/45115367/61728483-e3881200-ada7-11e9-8472-09df2736dbac.png)
不知道现在网站每天的流量大概有多少了，50000以下免费的，百度的接口效果还凑合，我以前用过类似的图片识别api，准确度基本上80%以上了。（不是广告...）

**Comment by redhood0** [comment]
实现思路大概是对截图一定区域进行切割（整张图的百分比），然后切割区域进行相似度识别和文字识别，就可以获取图内的信息了，然后对信息进行一定的处理就好啦。

**Comment by AlvISsReimu** [comment]
目前有几位dalao在研究识图模块，百度API好像是个不错的选择。谢谢建议！
Duplicate of #13
