### ISSUE TITLE
由部分上报带来的偏差问题

### ISSUE THREAD

**Issue by Prurite** [penguin-statistics/frontend-v1#25]
很多人刷概率/小概率材料时出货后才（想起）上报，会使总体统计出率偏高，希望对此进行考虑。（尽管我知道这个问题很难解）

**Comment by Ghost-M16A2** [comment]
emmmm,那个...我不小心把其它关当成1-4上传了两次数据，1-4数据里那两个代糖是不存在的，可以消一下吗？

**Comment by Prurite** [comment]
我也只是一个提issue的人…… 这些找管理吧

**Comment by Ghost-M16A2** [comment]
好吧

Prurite <notifications@github.com> 于 2019年8月2日周五 下午11:14写道：

**Comment by Ghost-M16A2** [comment]
emmmm，咋找

Captain PHY <2639403068x@gmail.com> 于 2019年8月2日周五 下午11:16写道：

**Comment by cyj5230** [comment]
> 很多人刷概率/小概率材料时出货后才（想起）上报，会使总体统计出率偏高，希望对此进行考虑。（尽管我知道这个问题很难解）

谢谢你的建议，我们已经在上报页面强调了这一点，并且内部也有一定的审核机制了。

**Comment by cyj5230** [comment]
> emmmm,那个...我不小心把其它关当成1-4上传了两次数据，1-4数据里那两个代糖是不存在的，可以消一下吗？

两个的话影响不大，删除个人历史功能就快做好了，如果不介意的话到时候可以自己消一下~
