### ISSUE TITLE
关于公开招募数据统计

### ISSUE THREAD

**Issue by wky9710** [penguin-statistics/frontend-v1#26]
能不能加一个公开招募的统计？

包含内容：
本次出现的5个tag
选择的tag
出货
//时间是否9h

因为先出干员后出tag基本是确认的，但保底机制和养蛊估计是玄学……加一个统计应该可以反推出池子的干员出现率，断个念想……
//来自养出来4个快速复活tag然后被亲4口的绝望doctor

**Comment by AlvISsReimu** [comment]
好像有贴吧dalao已经收集上千份数据了，目前这边团队在重构项目，不太有时间做公招统计（x
