### ISSUE TITLE
网站页面能正常访问，但是所有图片都要爬梯子才能显示

### ISSUE THREAD

**Issue by CannonFodderEX** [penguin-statistics/frontend-v1#27]
也许gh应该发代码相关的issue，不过微博和twitter我都没号。
网站页面能正常访问，但是所有图片都要爬梯子才能显示。
是不是图片的空间被墙了或者空间屏蔽了国内ip的访问？
补充：之前用了大概十几天，有时正常有时要爬梯子

**Comment by AlvISsReimu** [comment]
感觉国内应该对S3访问挺流畅的…？会不会是运营商抽风（
另外有计划要做境内cdn了，应该能大幅度提升访问体验…

**Comment by GalvinGao** [comment]
已经于 frontend-v2 修复~ Closing.
