### ISSUE TITLE
掉落结果查看refactor

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v1#6]
整体的请求方式需要重做。
大致流程：
加载网站时立刻拿到zones, stages和items。
点击“查看结果”tab后，根据data source是全平台还是本地，决定不同参数给result API发request，获得drop matrix以及lastUpdateTime，存放于localStorage中。以上操作为一次“结果刷新”。
之后无论是再次从别的地方进入查看结果tab，或者切换data Source，都要进行一次结果刷新。
若请求失败，则通过snackBar提示，但是原localStorage的matrix保持不变，以方便离线查看。

选定stage或者item后，对于按作战和按素材查看两种不同查看方式，需要各自实现函数，从localStorage的matrix中提取相应stage/item的结果，结合stageMap与itemMap生成最终table所需要的数据。

**Comment by GalvinGao** [comment]
Fixed in frontend-v2 ;)
Closing
